export const dummyChatHeadsData = [
  {
    id: 1,
    name: 'Fran Perez',
    image: '/images/shopOwner1.jpg',
    lastMessage:
      "You're welcome! If you have any other questions, just let me know.",
    lastSeen: '1h',
    type: 'shopOwner',
  },
  {
    id: 2,
    name: 'Brooklyn Simmons',
    image: '/images/shopOwner2.jpg',
    lastMessage: "Will follow up once it's dispatched.",
    lastSeen: '2d',
    type: 'shopOwner',
  },
  {
    id: 3,
    name: 'Guy Hawkins',
    image: '/images/shopOwner3.jpg',
    lastMessage: 'Order has been processed.',
    lastSeen: '2d',
    type: 'shopOwner',
  },
  {
    id: 4,
    name: 'Theresa Webb',
    image: '/images/shopOwner4.jpg',
    lastMessage: 'All packed and labeled.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 5,
    name: 'Courtney Henry',
    image: '/images/shopOwner5.jpg',
    lastMessage: 'Let me know the pickup time.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 6,
    name: 'Esther Howard',
    image: '/images/shopOwner6.jpg',
    lastMessage: 'Received, thank you.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 7,
    name: 'Ralph Edwards',
    image: '/images/shopOwner7.jpg',
    lastMessage: 'Can we schedule it tomorrow?',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 8,
    name: 'Eleanor Pena',
    image: '/images/shopOwner8.jpg',
    lastMessage: 'Ready for pickup anytime.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 9,
    name: 'Wade Warren',
    image: '/images/shopOwner9.jpg',
    lastMessage: 'Packing now, will confirm soon.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 10,
    name: 'Arlene McCoy',
    image: '/images/shopOwner10.jpg',
    lastMessage: 'Sent you the invoice.',
    lastSeen: '3 Sep',
    type: 'shopOwner',
  },
  {
    id: 11,
    name: 'Harvey Dent',
    image: '/images/driver1.jpg',
    lastMessage: 'On the way to pickup.',
    lastSeen: '4h',
    type: 'driver',
  },
  {
    id: 12,
    name: 'Diana Wayne',
    image: '/images/driver2.jpg',
    lastMessage: 'Stuck in traffic. ETA 20 mins.',
    lastSeen: '1d',
    type: 'driver',
  },
  {
    id: 13,
    name: 'Miles Morales',
    image: '/images/driver3.jpg',
    lastMessage: 'Delivered and signed.',
    lastSeen: '1h',
    type: 'driver',
  },
  {
    id: 14,
    name: 'Bruce Banner',
    image: '/images/driver4.jpg',
    lastMessage: 'Can’t find the shop. Help?',
    lastSeen: '5m',
    type: 'driver',
  },
  {
    id: 15,
    name: 'Steve Strange',
    image: '/images/driver5.jpg',
    lastMessage: 'Break time. Resuming in 10 mins.',
    lastSeen: '2h',
    type: 'driver',
  },
  {
    id: 16,
    name: 'Peter Quill',
    image: '/images/driver6.jpg',
    lastMessage: 'Package loaded.',
    lastSeen: 'Just now',
    type: 'driver',
  },
  {
    id: 17,
    name: 'Wade Wilson',
    image: '/images/driver7.jpg',
    lastMessage: 'Drop-off done.',
    lastSeen: '30m',
    type: 'driver',
  },
  {
    id: 18,
    name: 'Natasha Romanoff',
    image: '/images/driver8.jpg',
    lastMessage: 'Heading to next stop.',
    lastSeen: 'Today',
    type: 'driver',
  },
];

//dummy messages data
export const dummyMessagesData = [
  {
    id: 1,
    sender: 'self',
    message:
      'Hi Michelle, can you confirm if the stock is ready for pickup today?',
    timestamp: '19 hours ago',
  },
  {
    id: 2,
    sender: 'other',
    message:
      'Hi! Yes, the boxes are packed and ready. Just waiting for the driver.',
    timestamp: '1 day ago',
  },
  {
    id: 3,
    sender: 'self',
    message: 'Perfect. He should be there within the hour.',
    timestamp: '19 hours ago',
  },
  {
    id: 4,
    sender: 'other',
    message: "Got it. I'll have someone assist with loading.",
    timestamp: '1 day ago',
  },
  {
    id: 5,
    sender: 'self',
    message: 'Appreciate it. Let me know if anything changes.',
    timestamp: '19 hours ago',
  },
  {
    id: 6,
    sender: 'other',
    message: 'Sure thing!',
    timestamp: '1 day ago',
  },
  {
    id: 7,
    sender: 'self',
    message: 'Just confirming again: all items match the manifest?',
    timestamp: '18 hours ago',
  },
  {
    id: 8,
    sender: 'other',
    message: 'Yes, everything has been cross-checked.',
    timestamp: '17 hours ago',
  },
  {
    id: 9,
    sender: 'self',
    message: 'Thanks Michelle!',
    timestamp: '17 hours ago',
  },
  {
    id: 10,
    sender: 'other',
    message: "You're welcome! Talk soon.",
    timestamp: '16 hours ago',
  },
];
