import { DashboardCard } from '../dashboard/dashboard.types';
import newOrders from '@/../public/assets/images/new-orders.png';
import activeDriver from '@/../public/assets/images/truck_frame.png';
import pendingPayments from '@/../public/assets/images/pending_payments_frame.png';
import totalRevenue from '@/../public/assets/images/total_revenue_frame.png';
import revenueCod from '@/../public/assets/images/revenue_cod_frame.png';
import revenueOnline from '@/../public/assets/images/revenue_online_frame.png';

export const dashboardCards: DashboardCard[] = [
  {
    id: 'new-orders',
    title: 'New Orders',
    value: 15,
    icon: newOrders,
    altText: 'new orders',
    className: 'gap-0.5',
  },
  {
    id: 'active-drivers',
    title: 'Active Driver',
    value: 120,
    icon: activeDriver,
    altText: 'active driver',
  },
  {
    id: 'pending-payments',
    title: 'Pending Payments',
    value: '$1250',
    icon: pendingPayments,
    altText: 'pending payments',
  },
  {
    id: 'total-revenue',
    title: 'Total Revenue',
    value: '$2500',
    icon: totalRevenue,
    altText: 'total revenue',
  },
  {
    id: 'revenue-cod',
    title: 'Revenue COD',
    value: '$1250',
    icon: revenueCod,
    altText: 'revenue cod',
  },
  {
    id: 'revenue-online',
    title: 'Revenue Online',
    value: '$1250',
    icon: revenueOnline,
    altText: 'revenue online',
  },
];

//new orders dummy data

export const dummyNewOrdersData = [
  {
    orderId: 'Order # 56231LK',
    shopOwner: 'John Doe',
    shopOwnerImage: '/images/shopOwner1.jpg',
    driver: null,
    deliveryDate: '2025-04-26',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56232LK',
    shopOwner: 'Jane Smith',
    shopOwnerImage: '/images/shopOwner2.jpg',
    driver: '4',
    deliveryDate: '2025-04-26',
    payment: 'COD',
    paymentTypeStyle: 'success',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56233LK',
    shopOwner: 'Bob Marley',
    shopOwnerImage: '/images/shopOwner3.jpg',
    driver: null,
    deliveryDate: '2025-04-26',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56234LK',
    shopOwner: 'Alice Johnson',
    shopOwnerImage: '/images/shopOwner4.jpg',
    driver: '2',
    deliveryDate: '2025-04-26',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56235LK',
    shopOwner: 'Charlie Puth',
    shopOwnerImage: '/images/shopOwner5.jpg',
    driver: null,
    deliveryDate: '2025-04-26',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56236LK',
    shopOwner: 'Diana Prince',
    shopOwnerImage: '/images/shopOwner6.jpg',
    driver: '3',
    deliveryDate: '2025-04-27',
    payment: 'COD',
    paymentTypeStyle: 'success',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56237LK',
    shopOwner: 'Bruce Wayne',
    shopOwnerImage: '/images/shopOwner7.jpg',
    driver: null,
    deliveryDate: '2025-04-27',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56238LK',
    shopOwner: 'Clark Kent',
    shopOwnerImage: '/images/shopOwner8.jpg',
    driver: '1',
    deliveryDate: '2025-04-27',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56239LK',
    shopOwner: 'Lois Lane',
    shopOwnerImage: '/images/shopOwner9.jpg',
    driver: null,
    deliveryDate: '2025-04-27',
    payment: 'COD',
    paymentTypeStyle: 'success',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56240LK',
    shopOwner: 'Peter Parker',
    shopOwnerImage: '/images/shopOwner10.jpg',
    driver: '5',
    deliveryDate: '2025-04-28',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56241LK',
    shopOwner: 'Tony Stark',
    shopOwnerImage: '/images/shopOwner11.jpg',
    driver: null,
    deliveryDate: '2025-04-28',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56242LK',
    shopOwner: 'Steve Rogers',
    shopOwnerImage: '/images/shopOwner12.jpg',
    driver: '7',
    deliveryDate: '2025-04-28',
    payment: 'COD',
    paymentTypeStyle: 'success',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56243LK',
    shopOwner: 'Natasha Romanoff',
    shopOwnerImage: '/images/shopOwner13.jpg',
    driver: null,
    deliveryDate: '2025-04-28',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56244LK',
    shopOwner: 'Wanda Maximoff',
    shopOwnerImage: '/images/shopOwner14.jpg',
    driver: '6',
    deliveryDate: '2025-04-28',
    payment: 'Card',
    paymentTypeStyle: 'primary',
    address: '20 Greenway Drive, San Diego, CA',
  },
  {
    orderId: 'Order # 56245LK',
    shopOwner: 'Vision',
    shopOwnerImage: '/images/shopOwner15.jpg',
    driver: null,
    deliveryDate: '2025-04-28',
    payment: 'COD',
    paymentTypeStyle: 'success',
    address: '20 Greenway Drive, San Diego, CA',
  },
];
