export const dummyDriversData = [
  {
    id: '1',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane1@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver1.jpg',
  },
  {
    id: '2',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane2@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver2.jpg',
  },
  {
    id: '3',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane3@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver3.jpg',
  },
  {
    id: '4',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane4@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver4.jpg',
  },
  {
    id: '5',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane5@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver5.jpg',
  },
  {
    id: '6',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane6@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver6.jpg',
  },
  {
    id: '7',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane7@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver7.jpg',
  },
  {
    id: '8',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane8@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver8.jpg',
  },
  {
    id: '9',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane9@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver9.jpg',
  },
  {
    id: '10',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane10@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver10.jpg',
  },
  {
    id: '11',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane11@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver11.jpg',
  },
  {
    id: '12',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane12@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver12.jpg',
  },
  {
    id: '13',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane13@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver13.jpg',
  },
  {
    id: '14',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane14@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver14.jpg',
  },
  {
    id: '15',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane15@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver15.jpg',
  },
  {
    id: '16',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane16@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver16.jpg',
  },
  {
    id: '17',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane17@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver17.jpg',
  },
  {
    id: '18',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane18@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver18.jpg',
  },
  {
    id: '19',
    driver: 'John Doe',
    vehicle: 'Volvo FH16',
    email: 'jane19@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'En Route',
    profilePicture: '/images/driver19.jpg',
  },
  {
    id: '20',
    driver: 'John Doe check',
    vehicle: 'Volvo FH16',
    email: 'jane20@gmail.com',
    phoneNumber: '+92 123 456 7890',
    status: 'Available',
    profilePicture: '/images/driver20.jpg',
  },
];
