export const dummyShopOwnersData = [
  {
    id: '1',
    driver: 'Albert Dan',
    email: 'jane1@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner1.jpg',
  },
  {
    id: '2',
    driver: 'Albert Dan',
    email: 'jane2@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner2.jpg',
  },
  {
    id: '3',
    driver: 'Albert Dan',
    email: 'jane3@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner3.jpg',
  },
  {
    id: '4',
    driver: 'Albert Dan',
    email: 'jane4@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner4.jpg',
  },
  {
    id: '5',
    driver: 'Albert Dan',
    email: 'jane5@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner5.jpg',
  },
  {
    id: '6',
    driver: 'Albert Dan',
    email: 'jane6@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner6.jpg',
  },
  {
    id: '7',
    driver: 'Albert Dan',
    email: 'jane7@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner7.jpg',
  },
  {
    id: '8',
    driver: 'Albert Dan',
    email: 'jane8@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner8.jpg',
  },
  {
    id: '9',
    driver: 'Albert Dan',
    email: 'jane9@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner9.jpg',
  },
  {
    id: '10',
    driver: 'Albert Dan',
    email: 'jane10@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner10.jpg',
  },
  {
    id: '11',
    driver: 'Albert Dan',
    email: 'jane11@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner11.jpg',
  },
  {
    id: '12',
    driver: 'Albert Dan',
    email: 'jane12@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner12.jpg',
  },
  {
    id: '13',
    driver: 'Albert Dan',
    email: 'jane13@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner13.jpg',
  },
  {
    id: '14',
    driver: 'Albert Dan',
    email: 'jane14@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner14.jpg',
  },
  {
    id: '15',
    driver: 'Albert Dan',
    email: 'jane15@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner15.jpg',
  },
  {
    id: '16',
    driver: 'Albert Dan',
    email: 'jane16@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner16.jpg',
  },
  {
    id: '17',
    driver: 'Albert Dan',
    email: 'jane17@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner17.jpg',
  },
  {
    id: '18',
    driver: 'Albert Dan',
    email: 'jane18@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner18.jpg',
  },
  {
    id: '19',
    driver: 'Albert Dan',
    email: 'jane19@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner19.jpg',
  },
  {
    id: '20',
    driver: 'Albert Dan check',
    email: 'jane20@gmail.com',
    phoneNumber: '+92 123 456 7890',
    storeName: 'InMart',
    storeAddress: '20 Greenway Dr, San Diego, CA',
    profilePicture: '/images/shopOwner20.jpg',
  },
];
